#Isin() function understanding
pandas Series. isin() function is used to filter the DataFrame rows that contain a list of values. When it is called on Series, it returns a Series of booleans indicating if each element is in values, True when present, False when not. You can pass this series to the DataFrame to filter the rows.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd

# Set display options to show maximum columns
pd.set_option('display.max_columns', None)

# Set display options to show maximum columns
pd.set_option('display.max_rows', None)

company = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CLIENTS/7. Dammy/Pandas/Fortune 500 2017 - Fortune 500.csv')

company.head(5)

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,Hqtel,Ceo,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,72716,479-273-4000,C. Douglas McMillon,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,68131,402-346-1400,Warren E. Buffett,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,408-996-1010,Timothy D. Cook,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,972-444-1000,Darren W. Woods,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,94104,415-983-8300,John H. Hammergren,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

##Q#1.Fetch the where the industries are `Petroleum Refining` and `Computers, Office Equipmen`?

In [ ]:
company[company['Industry'].isin(['Petroleum Refining','Computers, Office Equipment'])]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,Hqtel,Ceo,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,95014,408-996-1010,Timothy D. Cook,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,75039,972-444-1000,Darren W. Woods,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
18,19,Chevron,http://www.chevron.com,55200,Energy,Petroleum Refining,"San Ramon, CA",6001 Bollinger Canyon Rd.,San Ramon,CA,94583,925-842-1000,John S. Watson,Chairman & Chief Executive Officer,"6001 Bollinger Canyon Rd., San Ramon, CA 94583",CVX,Chevron Corporation,107567,-18.0,-497.0,-110.8,260078,145556.0
33,34,Phillips 66,http://www.phillips66.com,14800,Energy,Petroleum Refining,"Houston, TX",2331 CityWest Blvd.,Houston,TX,77042,281-293-6600,Greg C. Garland,Chairman & Chief Executive Officer,"2331 CityWest Blvd., Houston, TX 77042",PSX,Phillips 66,72396,-16.9,1555.0,-63.2,51653,22390.0
36,37,Valero Energy,http://www.valero.com,9996,Energy,Petroleum Refining,"San Antonio, TX",1 Valero Way,San Antonio,TX,78249,210-345-2000,Joseph W. Gorder,"Chairman, President & Chief Executive Officer","1 Valero Way, San Antonio, TX 78249",VLO,Valero Energy Corporation,70166,-14.2,2289.0,-42.6,46173,20024.0
40,41,Dell Technologies,http://www.delltechnologies.com,138000,Technology,"Computers, Office Equipment","Round Rock, TX",1 Dell Way,Round Rock,TX,78682,800-289-3355,Michael S. Dell,Chairman & Chief Executive Officer,"1 Dell Way, Round Rock, TX 78682",LOW,Dell Technologies Inc.,64806,18.1,-1672.0,21.5,118206,13243.0
50,51,Marathon Petroleum,http://www.marathonpetroleum.com,44460,Energy,Petroleum Refining,"Findlay, OH",539 S. Main St.,Findlay,OH,45840,419-422-2121,Gary R. Heminger,"Chairman, President & Chief Executive Officer","539 S. Main St., Findlay, OH 45840",MPC,Marathon Petroleum Corporation,55858,-13.5,1174.0,-58.8,44413,13557.0
60,61,HP,http://www.hp.com,49000,Technology,"Computers, Office Equipment","Palo Alto, CA",1501 Page Mill Rd.,Palo Alto,CA,94304,650-857-1501,Dion J. Weisler,"President, Chief Executive Officer & Director","1501 Page Mill Rd., Palo Alto, CA 94304",HPQ,HP Inc.,48238,-53.3,2496.0,-45.2,29010,-3889.0
116,117,Tesoro,http://www.tsocorp.com,6308,Energy,Petroleum Refining,"San Antonio, TX",19100 Ridgewood Pkwy.,San Antonio,TX,78259,210-626-6000,Gregory J. Goff,"Chairman, President & Chief Executive Officer","19100 Ridgewood Pkwy., San Antonio, TX 78259",TSO,Tesoro Corporation,24005,-14.7,734.0,-52.3,20398,5465.0
171,172,PBF Energy,http://www.pbfenergy.com,3165,Energy,Petroleum Refining,"Parsippany, NJ",1 Sylvan Way,Parsippany,NJ,7054,973-455-7500,Thomas J. Nimbley,Chairman & Chief Executive Officer,"1 Sylvan Way, Parsippany, NJ 07054",PBF,PBF Energy Inc.,15920,21.3,170.8,16.7,7622,2025.0
273,274,HollyFrontier,http://www.hollyfrontier.com,2676,Energy,Petroleum Refining,"Dallas, TX",2828 N. Harwood,Dallas,TX,75201,214-871-3555,George J. Damiris,"President, Chief Executive Officer & Director","2828 N. Harwood, Dallas, TX 75201",HFC,HollyFrontier Corporation,10536,-20.4,-260.5,-135.2,9436,4681.0
348,349,Western Refining,http://www.wnr.com,7134,Energy,Petroleum Refining,"El Paso, TX",212 N. Clark Dr.,El Paso,TX,79905,915-534-1400,Gregory J. Goff,Chief Executive Officer & Director,"212 N. Clark Dr., El Paso, TX 79905",FL,"Western Refining, Inc.",7743,-20.9,124.9,-69.3,5560,1697.0
408,409,NCR,http://www.ncr.com,33500,Technology,"Computers, Office Equipment","Duluth, GA",3097 Satellite Blvd.,Duluth,GA,30096,937-445-5000,William R. Nuti,Chairman & Chief Executive Officer,"3097 Satellite Blvd., Duluth, GA 30096",NCR,NCR Corporation,6543,2.7,270.0,25.7,7673,1542.0
479,480,Delek US Holdings,http://www.delekus.com,1326,Energy,Petroleum Refining,"Brentwood, TN",7102 Commerce Way,Brentwood,TN,37027,615-771-6701,Ezra Uzi Yemin,"Chairman, President & Chief Executive Officer","7102 Commerce Way, Brentwood, TN 37027",DK,"Delek US Holdings, Inc.",5414,-6.0,-153.7,-892.3,2985,992.0

##Q#2.Fetch me the dataframe where sector is financial and indutry is Utilities: Gas and Electric

In [ ]:
company['Sector'] = company['Sector'].str.strip()
company['Industry'] = company['Industry'].str.strip()

In [ ]:
company[company['Sector'].isin(['Financial']) & company['Hqlocation'].isin(['Omaha, NE'])]

Empty DataFrame
Columns: [Rank, Title, Website, Employees, Sector, Industry, Hqlocation, Hqaddr, Hqcity, Hqstate, Hqzip, Hqtel, Ceo, Ceo-title, Address, Ticker, Fullname, Revenues, Revchange, Profits, Prftchange, Assets, Totshequity]
Index: []

##Revision

##Q#1.Which sector has the highest average revenue among companies that have more than 50,000 employees and have experienced positive profit change?

- Any non-numeric values (like strings or missing values) are converted to NaN, preventing errors during filtering

In [ ]:
# Convert Employees to numbers, coerce invalid values to NaN
company['Employees'] = pd.to_numeric(company['Employees'], errors='coerce')
company['Prftchange'] = pd.to_numeric(company['Prftchange'], errors='coerce')

filtered_df = company[(company['Employees'] > 50000) & (company['Prftchange'] > 0)]

filtered_df.groupby('Sector')['Revenues'].mean().sort_values(ascending=False)

Sector
Wholesalers                      85638.666667
Technology                       62539.375000
Health Care                      58539.000000
Media                            55632.000000
Telecommunications               54703.000000
Industrials                      54197.500000
Food, Beverages & Tobacco        42121.666667
Financials                       38404.375000
Transportation                   35395.000000
Food & Drug Stores               34274.000000
Aerospace & Defense              33078.333333
Household Products               32132.333333
Retailing                        30970.818182
Apparel                          19219.500000
Hotels, Restaurants & Leisure    17434.666667
Motor Vehicles & Parts           14596.666667
Business Services                13833.666667
Name: Revenues, dtype: float64

##Q#2.Which industry has the highest total revenue, but only for companies where profit margins (profits/revenues) are greater than 5% and they have more than 100,000 employees?

In [ ]:
company['Employees'] = pd.to_numeric(company['Employees'], errors='coerce')
company['Profits'] = pd.to_numeric(company['Profits'], errors='coerce')
company['Revenues'] = pd.to_numeric(company['Revenues'], errors='coerce')

filtered_df = company[(company['Profits'] / company['Revenues'] > 0.05) & (company['Employees'] > 100000)]

filtered_df.groupby('Industry')['Revenues'].sum().sort_values(ascending=False)

Industry
Commercial Banks                                  375710
Telecommunications                                370169
Insurance: Property and Casualty (Stock)          223604
Computers, Office Equipment                       215639
Motor Vehicles and Parts                          184938
Aerospace and Defense                             151815
Information Technology Services                   143529
Industrial Machinery                              126661
Computer Software                                 122367
Specialty Retailers: Other                        116582
Pharmaceuticals                                    71890
Household and Personal Products                    71726
Food Consumer Products                             62799
Mail, Package, and Freight Delivery                60906
Food Services                                      59624
Electronics, Electrical Equipment                  59570
Semiconductors and Other Electronic Components     59387
Entertainment                                      55632
Health Care: Medical Facilities                    44747
Beverages                                          41863
Airlines                                           40180
Food and Drug Stores                               34274
Specialty Retailers: Apparel                       33184
Name: Revenues, dtype: int64



---



---

#Tolist

#list all the industries in the dataset

In [ ]:
unique_industries = company['Industry'].unique()
type(unique_industries)

numpy.ndarray

In [ ]:
unique_industries = unique_industries.tolist()
type(unique_industries)

list