In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CLIENTS/7. Dammy/Pandas/Fortune 500 2017 - Fortune 500.csv')
df.head()

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
0,1,Walmart,http://www.walmart.com,2300000,Retailing,General Merchandisers,"Bentonville, AR",702 S.W. Eighth St.,Bentonville,AR,...,"President, Chief Executive Officer & Director","702 S.W. Eighth St., Bentonville, AR 72716",WMT,"Wal-Mart Stores, Inc.",485873,0.8,13643.0,-7.2,198825,77798.0
1,2,Berkshire Hathaway,http://www.berkshirehathaway.com,367700,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",3555 Farnam St.,Omaha,NE,...,Chairman & Chief Executive Officer,"3555 Farnam St., Omaha, NE 68131",BRKA,Berkshire Hathaway Inc.,223604,6.1,24074.0,0,620854,283001.0
2,3,Apple,http://www.apple.com,116000,Technology,"Computers, Office Equipment","Cupertino, CA",1 Infinite Loop,Cupertino,CA,...,Chief Executive Officer & Director,"1 Infinite Loop, Cupertino, CA 95014",AAPL,"Apple, Inc.",215639,-7.7,45687.0,-14.4,321686,128249.0
3,4,Exxon Mobil,http://www.exxonmobil.com,72700,Energy,Petroleum Refining,"Irving, TX",5959 Las Colinas Blvd.,Irving,TX,...,Chairman & Chief Executive Officer,"5959 Las Colinas Blvd., Irving, TX 75039",XOM,Exxon Mobil Corporation,205004,-16.7,7840.0,-51.5,330314,167325.0
4,5,McKesson,http://www.mckesson.com,68000,Wholesalers,Wholesalers: Health Care,"San Francisco, CA",1 Post St.,San Francisco,CA,...,"Chairman, President & Chief Executive Officer","1 Post St., San Francisco, CA 94104",MCK,McKesson Corporation,192487,6.2,2258.0,53,56563,8924.0

In [ ]:
type(df)

pandas.core.frame.DataFrame

#FETCHING OF COLUMN

##1.Fetching 1 column

In [ ]:
#fething 1 column
df['Employees']

0      2300000
1       367700
2       116000
3        72700
4        68000
        ...
495      31000
496       4200
497       8500
498       4431
499     110000
Name: Employees, Length: 500, dtype: int64

In [ ]:
df.iloc[:,3]

0      2300000
1       367700
2       116000
3        72700
4        68000
        ...
495      31000
496       4200
497       8500
498       4431
499     110000
Name: Employees, Length: 500, dtype: int64

##1.Fetching multiple columns

In [ ]:
df[['Title','Employees']]

                  Title  Employees
0               Walmart    2300000
1    Berkshire Hathaway     367700
2                 Apple     116000
3           Exxon Mobil      72700
4              McKesson      68000
..                  ...        ...
495       Michaels Cos.      31000
496       Toll Brothers       4200
497               Yahoo       8500
498       Vistra Energy       4431
499      ABM Industries     110000

[500 rows x 2 columns]

In [ ]:
df.iloc[30:45,[1,3]]

                        Title  Employees
30                    Comcast     159000
31                        IBM     414400
32  State Farm Insurance Cos.      68234
33                Phillips 66      14800
34          Johnson & Johnson     126400
35           Procter & Gamble     105000
36              Valero Energy       9996
37                     Target     323000
38                Freddie Mac       5982
39                     Lowe’s     240000
40          Dell Technologies     138000
41                    MetLife      58000
42                      Aetna      49500
43                    PepsiCo     264000
44     Archer Daniels Midland      31800



---

#FETCHING OF ROW

- For fetching rows we have to rely on iloc function only!

##Fetch 1 row

In [ ]:
df.iloc[400]

Rank                                                     401
Title                                         Owens-Illinois
Website                                   http://www.o-i.com
Employees                                              27000
Sector                                             Materials
Industry                               Packaging, Containers
Hqlocation                                    Perrysburg, OH
Hqaddr                                   1 Michael Owens Way
Hqcity                                            Perrysburg
Hqstate                                                   OH
Hqzip                                                  43551
Hqtel                                           567-336-5000
Ceo                                          Andres A. Lopez
Ceo-title      President, Chief Executive Officer & Director
Address            1 Michael Owens Way, Perrysburg, OH 43551
Ticker                                                    OI
Fullname                                Owens-Illinois, Inc.
Revenues                                                6702
Revchange                                                8.9
Profits                                                209.0
Prftchange                                              54.8
Assets                                                  9135
Totshequity                                            254.0
Name: 400, dtype: object

In [ ]:
df.iloc[400:450:5]

,Rank,Title,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
400,401,Owens-Illinois,http://www.o-i.com,27000,Materials,"Packaging, Containers","Perrysburg, OH",1 Michael Owens Way,Perrysburg,OH,...,"President, Chief Executive Officer & Director","1 Michael Owens Way, Perrysburg, OH 43551",OI,"Owens-Illinois, Inc.",6702,8.9,209.0,54.8,9135,254.0
405,406,Activision Blizzard,http://www.activisionblizzard.com,9500,Technology,Computer Software,"Santa Monica, CA",3100 Ocean Park Blvd.,Santa Monica,CA,...,"President, Chief Executive Officer & Director","3100 Ocean Park Blvd., Santa Monica, CA 90405",ATVI,"Activision Blizzard, Inc.",6608,41.7,966.0,8.3,17452,9119.0
410,411,American Financial Group,http://www.afginc.com,7600,Financials,Insurance: Property and Casualty (Stock),"Cincinnati, OH",301 E. Fourth St.,Cincinnati,OH,...,"Co-President, Co-Chief Executive Officer & Dir...","301 E. Fourth St., Cincinnati, OH 45202",AFG,"American Financial Group, Inc.",6498,5.7,649.0,84.4,55072,4916.0
415,416,Dr Pepper Snapple Group,http://www.drpeppersnapplegroup.com,20000,"Food, Beverages & Tobacco",Beverages,"Plano, TX",5301 Legacy Dr.,Plano,TX,...,"President, Chief Executive Officer & Director","5301 Legacy Dr., Plano, TX 75024",DPS,"Dr Pepper Snapple Group, Inc.",6440,2.5,847.0,10.9,9791,2134.0
420,421,Builders FirstSource,http://www.bldr.com,14000,Materials,"Building Materials, Glass","Dallas, TX",2001 Bryan St.,Dallas,TX,...,Chief Executive Officer & Director,"2001 Bryan St., Dallas, TX 75201",BLDR,"Builders FirstSource, Inc.",6367,78.6,144.3,2.2,2910,310.0
425,426,iHeartMedia,http://www.iheartmedia.com,18700,Media,Entertainment,"San Antonio, TX",200 E. Basse Rd.,San Antonio,TX,...,Chairman & Chief Executive Officer,"200 E. Basse Rd., San Antonio, TX 78209",IHRT,"iHeartMedia, Inc.",6274,0.5,-296.3,-5.7,12862,-11021.0
430,431,Ameren,http://www.ameren.com,8629,Energy,Utilities: Gas and Electric,"St. Louis, MO",1901 Chouteau Ave.,St. Louis,MO,...,"Chairman, President & Chief Executive Officer","1901 Chouteau Ave., St. Louis, MO 63103",AEE,Ameren Corporation,6076,-0.4,653.0,3.7,24699,7103.0
435,436,Regions Financial,http://www.regions.com,22166,Financials,Commercial Banks,"Birmingham, AL",1900 Fifth Ave. N.,Birmingham,AL,...,"Chairman, President & Chief Executive Officer","1900 Fifth Ave. N., Birmingham, AL 35203",RF,Regions Financial Corporation,5967,5.2,1163.0,9.5,125968,16664.0
440,441,AK Steel Holding,http://www.aksteel.com,8500,Materials,Metals,"West Chester, OH",9227 Centre Pointe Dr.,West Chester,OH,...,Chief Executive Officer & Director,"9227 Centre Pointe Dr., West Chester, OH 45069",AKS,AK Steel Holding Corporation,5883,-12.1,-7.8,39.4,4036,-272.0
445,446,NVR,http://www.nvrinc.com,4900,Engineering & Construction,Homebuilders,"Reston, VA",11700 Plaza America Dr.,Reston,VA,...,"President, Chief Executive Officer & Director","11700 Plaza America Dr., Reston, VA 20190",NVR,"NVR, Inc.",5835,12.9,425.3,11.1,2644,1304.0

##Fetch multiple rows